---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: concourse-git-start

outputs:
- name: app-manifest-output

run:
  path: episodic-apps/ci/tasks/app-manifest-prep
